package com.demo.common.model;

import com.demo.common.model.base.BaseForm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Form extends BaseForm<Form> {
	public static final Form dao = new Form();
	
	public boolean updateForm(Form form){
		//jfinal强大的数据库方法
		return form.save();
	}
}
