package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	public User validatorUser(User user) {
		List<User> list = dao.find("select * from user where user_name = ?",user.get("user_name"));
		if(list.size() > 0){
			User targetUser = list.get(0);
			if(targetUser.get("user_psw").equals(user.get("user_psw"))){
				return user;
			}
		}
		return null;
	}
}
